name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release Provider
    runs-on: ubuntu-latest

    env:
      PROVIDER_NAME: jenkins

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --pinentry-mode loopback --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build Provider for ${{ matrix.goos }}_${{ matrix.goarch }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          BIN_NAME=terraform-provider-${{ env.PROVIDER_NAME }}_${VERSION}
          ZIP_NAME=${BIN_NAME}_${{ matrix.goos }}_${{ matrix.goarch }}.zip

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $BIN_NAME
          zip $ZIP_NAME $BIN_NAME

          echo "$ZIP_NAME" >> artifact-list.txt

      - name: Generate SHA256SUMS
        if: ${{ matrix.goos == 'linux' && matrix.goarch == 'amd64' }} # only once
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cat artifact-list.txt | xargs sha256sum > terraform-provider-${{ env.PROVIDER_NAME }}_${VERSION}_SHA256SUMS

      - name: Sign SHA256SUMS
        if: ${{ matrix.goos == 'linux' && matrix.goarch == 'amd64' }} # only once
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          gpg --batch --yes --pinentry-mode loopback --armor \
              --output terraform-provider-${{ env.PROVIDER_NAME }}_${VERSION}_SHA256SUMS.sig \
              --detach-sign terraform-provider-${{ env.PROVIDER_NAME }}_${VERSION}_SHA256SUMS
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.goos == 'linux' && matrix.goarch == 'amd64' }} # upload once
        with:
          token: ${{ secrets.GIT_TOKEN }}
          files: |
            terraform-provider-${{ env.PROVIDER_NAME }}_*.zip
            terraform-provider-${{ env.PROVIDER_NAME }}_*_SHA256SUMS
            terraform-provider-${{ env.PROVIDER_NAME }}_*_SHA256SUMS.sig
